<?php

declare(strict_types=1);

namespace HaythemBekir\LogMetrics\Domain\ValueObjects;

use DateTimeInterface;
use HaythemBekir\LogMetrics\Domain\Config\AppearanceConfig;
use Illuminate\Support\Str;

final class DiscordMessage
{
    private const MAX_MESSAGE_LENGTH = 2048;
    private const MAX_FIELD_VALUE_LENGTH = 1024;

    public function __construct(
        public readonly string $webhookUrl,
        public readonly string $title,
        public readonly string $description,
        public readonly int $color,
        public readonly array $fields,
        public readonly ?string $footer = null,
        public readonly ?string $timestamp = null,
    ) {}

    public static function forLogAlert(
        string $webhookUrl,
        LogLevel $level,
        string $message,
        LogContext $context,
        AppearanceConfig $appearance,
        string $environment,
    ): self {
        $fields = [
            ['name' => 'Level', 'value' => $level->emoji() . ' ' . ucfirst($level->value), 'inline' => true],
            ['name' => 'Environment', 'value' => $environment, 'inline' => true],
            ['name' => 'Time', 'value' => now()->toDateTimeString(), 'inline' => true],
        ];

        if (! $context->isEmpty()) {
            $fields[] = [
                'name' => 'Context',
                'value' => '```json' . "\n" . $context->toJson(self::MAX_FIELD_VALUE_LENGTH - 20) . "\n" . '```',
                'inline' => false,
            ];
        }

        return new self(
            webhookUrl: $webhookUrl,
            title: "Log Alert: {$level->value}",
            description: Str::limit($message, self::MAX_MESSAGE_LENGTH),
            color: $appearance->getColorForLevel($level->value),
            fields: $fields,
            timestamp: now()->toIso8601String(),
        );
    }

    public static function forDailyReport(
        string $webhookUrl,
        DateTimeInterface $date,
        int $totalLogs,
        array $byLevel,
        array $byChannel,
        array $topErrors,
        AppearanceConfig $appearance,
        ?array $errorLinks = null,
    ): self {
        $hasErrors = ($byLevel['error'] ?? 0) > 0
            || ($byLevel['critical'] ?? 0) > 0
            || ($byLevel['alert'] ?? 0) > 0
            || ($byLevel['emergency'] ?? 0) > 0;

        $fields = [
            ['name' => 'Total Logs', 'value' => (string) $totalLogs, 'inline' => true],
        ];

        // Add level counts
        foreach (['emergency', 'alert', 'critical', 'error', 'warning', 'notice', 'info', 'debug'] as $level) {
            $count = $byLevel[$level] ?? 0;
            if ($count > 0) {
                $levelEnum = LogLevel::fromString($level);
                $fields[] = [
                    'name' => ucfirst($level),
                    'value' => $levelEnum->emoji() . ' ' . $count,
                    'inline' => true,
                ];
            }
        }

        // Add channel breakdown if available
        if (! empty($byChannel)) {
            $channelText = '';
            foreach (array_slice($byChannel, 0, 5) as $channel => $count) {
                $channelText .= "{$channel}: {$count}\n";
            }
            $fields[] = [
                'name' => 'By Channel',
                'value' => $channelText ?: 'None',
                'inline' => false,
            ];
        }

        // Add top errors if available
        if (! empty($topErrors)) {
            $errorsText = '';
            foreach (array_slice($topErrors, 0, 5) as $index => $error) {
                $errorMessage = Str::limit($error['message'], 80);

                // Add clickable link if available
                if ($errorLinks !== null && isset($errorLinks[$index])) {
                    $errorMessage = "[{$errorMessage}]({$errorLinks[$index]})";
                }

                $errorsText .= "• {$error['count']}x: {$errorMessage}\n";
            }
            $fields[] = [
                'name' => 'Top Recurring Errors',
                'value' => $errorsText,
                'inline' => false,
            ];
        }

        return new self(
            webhookUrl: $webhookUrl,
            title: 'Daily Log Report - ' . $date->format('Y-m-d'),
            description: $hasErrors
                ? 'Issues detected in the last 24 hours.'
                : 'All systems operating normally.',
            color: $hasErrors ? $appearance->getColorForLevel('warning') : 0x00FF00,
            fields: $fields,
            footer: 'Generated by Laravel Discord Logger',
            timestamp: now()->toIso8601String(),
        );
    }

    public function toEmbed(): array
    {
        $embed = [
            'title' => $this->title,
            'description' => $this->description,
            'color' => $this->color,
            'fields' => $this->fields,
        ];

        if ($this->footer !== null) {
            $embed['footer'] = ['text' => $this->footer];
        }

        if ($this->timestamp !== null) {
            $embed['timestamp'] = $this->timestamp;
        }

        return $embed;
    }
}
